'use client'
import Nav from '../components/Nav'

const gold = '#C8A24A'

export default function TermsPage() {
  return (
    <main style={{ backgroundColor: '#050505', color: '#fff', fontFamily: 'Inter,system-ui,sans-serif', minHeight: '100vh' }}>
      <Nav />
      <section style={{ maxWidth: '800px', margin: '0 auto', padding: '80px 48px' }}>
        <div style={{ fontSize: '11px', color: gold, letterSpacing: '0.25em', textTransform: 'uppercase', marginBottom: '16px', fontWeight: '600' }}>Legal</div>
        <h1 style={{ fontSize: '48px', fontWeight: '800', marginBottom: '12px', letterSpacing: '-0.02em' }}>Terms of Service</h1>
        <p style={{ fontSize: '13px', color: '#555', marginBottom: '48px' }}>Last updated: June 2026</p>

        {[
          { title: '1. Acceptance of Terms', body: 'By accessing or using the BEI platform at officialbei.com, you agree to be bound by these Terms of Service. If you do not agree, do not use the platform. These terms apply to all users, including those on free and paid plans.' },
          { title: '2. The Service', body: 'BEI provides a business intelligence and execution platform that analyses business data to identify constraints, generate recommendations, and support deployment of improvements. The platform includes the Business MRI, Business Twin, constraint detection engine, opportunity engine, deployment engine, and BEI Intelligence monitoring.' },
          { title: '3. Accounts and Access', body: 'You must provide accurate information when creating an account. You are responsible for maintaining the security of your account credentials. BEI reserves the right to suspend or terminate accounts that violate these terms or are used fraudulently.' },
          { title: '4. Subscriptions and Billing', body: 'Paid subscriptions are billed monthly via Stripe. Prices are as displayed on our pricing page. You may cancel at any time and will retain access until the end of your current billing period. BEI does not offer refunds for partial months. Prices may change with 30 days notice.' },
          { title: '5. Acceptable Use', body: 'You agree not to misuse the platform, attempt to reverse-engineer the intelligence systems, scrape or harvest data, introduce malware, or use BEI for any unlawful purpose. You may not resell or sublicense access to BEI without written permission.' },
          { title: '6. Intellectual Property', body: 'All platform technology, intelligence architecture, scoring systems, and content are the intellectual property of Business Execution Intelligence. Your business data remains yours. By submitting data to BEI, you grant us a licence to process it for the purpose of delivering the service and improving our intelligence models.' },
          { title: '7. Intelligence Output Disclaimer', body: 'BEI\'s intelligence outputs — including constraint identification, opportunity quantification, and deployment recommendations — are generated by automated systems and are advisory in nature. They do not constitute professional business, financial, or legal advice. You remain solely responsible for decisions made based on BEI outputs.' },
          { title: '8. Limitation of Liability', body: 'To the fullest extent permitted by law, BEI shall not be liable for any indirect, incidental, or consequential damages arising from use of the platform. Our total liability to you shall not exceed the amount you paid to BEI in the 12 months preceding the claim.' },
          { title: '9. Service Availability', body: 'We aim for high availability but do not guarantee uninterrupted access. We may perform maintenance, updates, or modifications that temporarily affect availability. We will provide reasonable notice of planned downtime where possible.' },
          { title: '10. Termination', body: 'Either party may terminate the relationship at any time. BEI may terminate your access immediately for breach of these terms. Upon termination, your right to access the platform ceases and your data will be deleted in accordance with our Privacy Policy.' },
          { title: '11. Governing Law', body: 'These terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.' },
          { title: '12. Changes to Terms', body: 'We may update these terms from time to time. We will notify you of material changes via email or platform notification. Continued use after changes constitutes acceptance.' },
        ].map(s => (
          <div key={s.title} style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '18px', fontWeight: '700', color: gold, marginBottom: '12px' }}>{s.title}</h2>
            <p style={{ fontSize: '15px', color: '#999', lineHeight: '1.9' }}>{s.body}</p>
          </div>
        ))}
      </section>
      <footer style={{ padding: '32px 48px', borderTop: '1px solid #111', textAlign: 'center' }}>
        <p style={{ fontSize: '12px', color: '#444' }}>© 2026 Business Execution Intelligence · <a href="/terms" style={{ color: '#444', textDecoration: 'none' }}>Terms</a> · <a href="/privacy" style={{ color: '#444', textDecoration: 'none' }}>Privacy</a></p>
      </footer>
    </main>
  )
}
